spring:
  datasource:
    username: hsp
    password: 123456
    url: jdbc:h2:file:./blogDB
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode:
      continue-on-error: true
